# Generated by Django 4.2.16 on 2024-11-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_manager", "0002_alter_feedback_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date"]},
        ),
    ]
